bumped lammps version (#1425)
* bumped lammps and python versions

* Fixed easily fixable tests [no ci]

Tests still broken:
test_create_interaction_style: AttributeError, System has no attribute 'style'
test_number_interaction_types: giving wrong values
test_number_interactions: giving wrong values
test_atom_type_mass: giving lowest possible float as mass

* Make some tests more robust across lammps versions

* moved lammps version to env variable

* typo

* update tests and revert bad change to _set_momentum_removers

---------

Co-authored-by: Jacob Wilkins <jacob.wilkins@stfc.ac.uk>